apiVersion: v1
kind: Service
metadata:
  name: hello-world-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30001
    targetPort: 8082
    port: 8082
  selector:
    app: hello-world-kubernetes
